# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\oongj\Desktop\mdp\MDP_Algo_test\Simulation\hamiltonian.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hamiltonian(object):
    def setupUi(self, Hamiltonian):
        Hamiltonian.setObjectName("Hamiltonian")
        Hamiltonian.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Hamiltonian)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Hamiltonian)
        self.buttonBox.accepted.connect(Hamiltonian.accept)
        self.buttonBox.rejected.connect(Hamiltonian.reject)
        QtCore.QMetaObject.connectSlotsByName(Hamiltonian)

    def retranslateUi(self, Hamiltonian):
        _translate = QtCore.QCoreApplication.translate
        Hamiltonian.setWindowTitle(_translate("Hamiltonian", "Dialog"))
